### ISSUE TITLE
Create release version

### ISSUE THREAD

**Issue by andreybolonin** [fungio/FungioDataExporterBundle#3]
http://i.imgur.com/6l6n1RQ.png

I use insight.sensiolabs.com for analyze our project.

What about to create release v0.1 to avoid this minor bug ?

**Comment by fungio** [comment]
Here you go : https://github.com/fungio/FungioDataExporterBundle/tree/0.1.x

**Comment by andreybolonin** [comment]
Yep, thanks a lot.
